name: etl_film_analytics
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - intel-openmp=2019.4
  - krb5=1.17.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libpq=12.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1j
  - pandas=1.2.1
  - pip=20.3.3
  - psycopg2=2.8.6
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tabulate=0.8.7
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - tqdm==4.57.0
